# Generated by Django 3.2.6 on 2021-08-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pan_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('pan_number', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=10)),
            ],
        ),
    ]
